import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { motion } from "framer-motion";
import { Ruler, Wrench, Package, Camera, Clock, ShieldCheck } from "lucide-react";
import sectionProjeto from "@/assets/section-projeto.jpg";
import SectionBlock from "./SectionBlock";

export default function ProjetoSection() {
  const inputs = ["Planta do imóvel e medidas reais", "Perfil do público-alvo (executivo, turista, nômade digital)", "Orçamento disponível para reforma", "Fotos do estado atual", "Preferências de estilo e referências visuais"];
  const pipeline = [{ step: "Projeto", desc: "Layout otimizado, 3D e detalhamento técnico", duration: "2–3 semanas", icon: Ruler }, { step: "Execução", desc: "Fornecedores homologados, obra acompanhada", duration: "3–5 semanas", icon: Wrench }, { step: "Marcenaria", desc: "Sob medida, instalação coordenada", duration: "2–3 semanas", icon: Package }, { step: "Decoração", desc: "Montagem final, fotos profissionais", duration: "1 semana", icon: Camera }];

  return (
    <SectionBlock id="projeto" title="Projeto Arquitetônico Personalizado" takeaway="Como um bom projeto multiplica o valor percebido do seu studio.">
      <div className="rounded-2xl overflow-hidden mb-8 shadow-sm ring-1 ring-border"><img src={sectionProjeto} alt="Planta e renderização 3D de studio" className="w-full h-40 md:h-64 object-cover" loading="lazy" /></div>
      <h3 className="font-display text-xl font-bold text-foreground mb-4">O que você precisa fornecer</h3>
      <Card className="border-border mb-8"><CardContent className="p-5 font-body"><ul className="space-y-2">{inputs.map((item, i) => <li key={i} className="flex items-center gap-3"><div className="h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0"><span className="text-xs font-bold text-primary">{i + 1}</span></div><span className="text-sm text-foreground">{item}</span></li>)}</ul></CardContent></Card>
      <h3 className="font-display text-xl font-bold text-foreground mb-4">Método Bwild — Pipeline</h3>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">{pipeline.map((p, i) => <motion.div key={p.step} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}><Card className="border-border h-full"><CardContent className="p-5 text-center"><div className="h-10 w-10 mx-auto rounded-full bg-primary/10 flex items-center justify-center mb-3"><p.icon className="text-primary" size={20} /></div><p className="font-display font-bold text-foreground text-sm">{p.step}</p><p className="text-xs text-muted-foreground mt-1">{p.desc}</p><Badge variant="secondary" className="mt-2 font-body text-xs"><Clock size={10} className="mr-1" />{p.duration}</Badge></CardContent></Card></motion.div>)}</div>
      <div className="bg-primary/5 border border-primary/20 rounded-lg p-5 flex items-start gap-3"><ShieldCheck className="text-primary mt-0.5 flex-shrink-0" size={22} /><div><p className="font-display font-bold text-foreground text-sm mb-1">Previsibilidade de prazo e orçamento fechado</p><p className="text-sm text-muted-foreground">O método Bwild trabalha com orçamento fechado e cronograma definido desde o início. Sem surpresas — você sabe exatamente quanto vai investir e quando o studio estará pronto para operar.</p></div></div>
      <Accordion type="multiple" className="mt-4 font-body">
        <AccordionItem value="etapas"><AccordionTrigger className="text-primary font-semibold">O que acontece em cada etapa</AccordionTrigger><AccordionContent><div className="space-y-4 text-sm"><div><p className="font-semibold text-foreground">1. Projeto (2–3 semanas)</p><p className="text-muted-foreground">Entregáveis: planta humanizada, layout 3D renderizado, detalhamento técnico para execução, lista de materiais e orçamento fechado. O investidor precisa fornecer a planta do imóvel, fotos e briefing de estilo. Aprovação do projeto antes de iniciar a obra.</p></div><div><p className="font-semibold text-foreground">2. Execução (3–5 semanas)</p><p className="text-muted-foreground">Entregáveis: obra completa (pintura, elétrica, iluminação, piso se necessário). Fornecedores homologados pela Bwild executam com acompanhamento semanal. Relatório de progresso por milestone. O investidor recebe atualizações semanais com fotos.</p></div><div><p className="font-semibold text-foreground">3. Marcenaria (2–3 semanas)</p><p className="text-muted-foreground">Entregáveis: armários, bancadas e nichos sob medida. Produção em paralelo com a obra. Instalação coordenada para evitar retrabalho. O investidor aprova amostras de acabamento antes da produção.</p></div><div><p className="font-semibold text-foreground">4. Decoração (1 semana)</p><p className="text-muted-foreground">Entregáveis: montagem completa (mobília, enxoval, objetos decorativos), fotos profissionais para o anúncio, guia de reposição. O investidor recebe o studio pronto para operar com todas as fotos otimizadas para as plataformas.</p></div></div></AccordionContent></AccordionItem>
        <AccordionItem value="diferencial"><AccordionTrigger className="text-primary font-semibold">Diferencial do método Bwild</AccordionTrigger><AccordionContent><p className="text-sm text-muted-foreground leading-relaxed">Orçamento fechado desde o projeto — sem surpresas. Cronograma com milestone por semana e penalidades para atrasos. Fornecedores homologados com histórico comprovado em short stay. Garantia de 1 ano em todos os serviços. A experiência de +200 studios permite antecipar problemas comuns e evitar desperdícios que investidores de primeira viagem não conseguem prever.</p></AccordionContent></AccordionItem>
      </Accordion>
    </SectionBlock>
  );
}
